

<fieldset>
    <legend><?php echo  $this->legende  ?></legend>

    <?php foreach ($this->forschungen as $work) :?>
        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_id')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_autorid')); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_autor_rollid')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_titel')); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_typ')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_betreuer1')); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_betreuer1_rollid')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_betreuer2')); ?>
            </div>
        </div>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_istabgeschlossen')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_abschlussjahr')); ?>
            </div>
        </div>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_semester')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_bemerkungen')); ?>
            </div>
        </div>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_abstract')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_imwebsichtbar')); ?>
            </div>
        </div>



        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_DOI')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_ISSN')); ?>
            </div>
        </div>



        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_ISBN')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_ZORA')); ?>
            </div>
        </div>



        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_FDB')); ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_URL')); ?>
            </div>
        </div>



        <div class="row-fluid">
            <div class="span10">
                <?php echo  $this->formRowTwb($work->get('qarb_arb_changed')); ?>
            </div>
        </div>




    <?php endforeach; ?>

</fieldset>
