<form id="search-form" class="searchForm form-search" action="<?php echo $this->url($route, array('action' => 'search')); ?>">
	<div class="input-append">
		<input id="search-query" name="query" type="text" class="search-query" placeholder="Search">
		<button type="submit" class="btn"><?php echo $this->translate('action_search ', 'Libadmin') ?></button>
	</div>
</form>
<ul id="search-results-list" class="searchResultList nav nav-tabs nav-stacked">
	<?php echo $this->render('fsw/global/search'); ?>
</ul>

