<?php


$this->headTitle("Forschungsarbeiten");


$form = $this->form;

$form->setAttribute('action', $this->url(
    'forschungAdmin',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();


$forschungsarbeiten = $form->get('forschungsarbeiten');
$medien = $form->get('medien');
$zoradocs = $form->get("zoradocs");



$saveButtonLabel = "Speichern";

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formLabel()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

?>



<?php echo  $this->formTwb()->openTag($form, $formType) ?>


    <fieldset>
        <div class="topButtons">

            <a href="<?php echo  $this->url('personenaktivitaet', array('action' => 'closeContent')); ?>"
               class="ajaxButton closeButton btn btn-medium" id="closebutton">
                "Hier schliessen"
            </a>
        </div>
    </fieldset>

    <h3>
        <?php echo $this->escapeHtml($title) .
            ': ' . $this->person->getPers_name() . ', ' . $this->person->getPers_vorname(); ?>

    </h3>


<?php echo  $this->ztbFlashMessenger()->render() ?>

<div class="tabbable">
    <ul class="nav nav-tabs formTabs">
        <li class="active"><a href="#forschungsarbeiten"><?php echo  $this->translate('Qualifikationsarbeiten ', 'Libadmin') ?></a></li>
        <li><a href="#medien"><?php echo  $this->translate('Medien', 'Libadmin') ?></a></li>
        <li><a href="#zoradocs"><?php echo  $this->translate('Zora Docs', 'Libadmin') ?></a></li>
    </ul>


    <div class="tab-content">
        <div class="tab-pane active" id="forschungsarbeiten">
            <fieldset class="general">
                <legend><?php echo  $this->translate('Liste der Qualifikationsarbeiten ','Libadmin') ?></legend>
                    <?php foreach ($forschungsarbeiten as $forschung) :?>
                        <div class="row-fluid">
                            <div class="span6">
                                <?php echo  $this->formRowTwb($forschung->get('qarb_arb_id')); ?>
                            </div>
                            <div class="span6">
                                <?php echo  $this->formRowTwb($forschung->get('qarb_arb_titel')); ?>
                            </div>
                        </div>

                    <?php endforeach; ?>

            </fieldset>



        </div>


        <div class="tab-pane" id="medien">

            <fieldset class="general">
                <legend><?php echo  $this->translate('Liste der Medien ','Libadmin') ?></legend>
                <?php foreach ($medien as $medium) :?>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php echo  $this->formRowTwb($medium->get('id')); ?>
                        </div>
                        <div class="span6">
                            <?php echo  $this->formRowTwb($medium->get('gespraechstitel')); ?>
                        </div>

                    </div>

                <?php endforeach; ?>

            </fieldset>


        </div>

        <div class="tab-pane" id="zoradocs">

            <fieldset class="general">
                <legend><?php echo  $this->translate('Liste der Zoraarbeiten ','Libadmin') ?></legend>
                <?php $numberdocs = 0 ?>
                <?php foreach ($zoradocs as $zoradoc) :?>


                    <?php if ($numberdocs != 0) : ?>
                        <div class="row-fluid">
                            <div>==========================================================================================</div>
                        </div>
                    <?php endif;  ?>

                    <div class="row-fluid">

                        <div class="span5"><?php echo $this->formHidden($zoradoc->get('oai_identifier')); ?></div>
                    </div>


                    <div class="row-fluid">
                        <div class="span6">
                            <?php echo  $this->formRowTwb($zoradoc->get('title')); ?>
                        </div>
                        <div class="span6">
                            <?php $identifier = $zoradoc->get('oai_identifier')->getValue();
                            $matches = array();

                            $grepresult =  preg_match('/oai:www\.zora\.uzh\.ch:(\d+)$/',$identifier,$matches);
                            ?>
                            <a  target="_blank" href='<?php echo   'http://www.zora.uzh.ch/' .   $matches[1] ?>'>Link zu Zora</a>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <?php echo  $this->formRowTwb($zoradoc->get('coverlink')); ?>
                        </div>
                        <div class="span2" style="margin-left: 30px;">
                            <a href="#"
                               class="updateCoverLink" data-currentIndex="<?php echo $numberdocs; ?>">update Coverlink</a>
                        </div>
                    </div>

                    <?php $numberdocs++ ?>


                <?php endforeach; ?>

            </fieldset>


        </div>




</div>


<?php echo  $this->form()->closeTag(); ?>