<?php


$this->headTitle("Forschungsarbeiten");


$form = $this->form;

$form->setAttribute('action', $this->url(
    'forschung',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();


$forschungsarbeiten = $form->get('forschungsarbeiten');
$medien = $form->get('medien');
$zoradocs = $form->get("zoradocs");



$saveButtonLabel = "Speichern";

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formLabel()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

?>



<?php echo  $this->formTwb()->openTag($form, $formType) ?>
    <div class="topButtons">
        <input type="submit" value="<?php echo  $this->escapeHtml($saveButtonLabel) ?>"
               class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
        <a href="<?php echo  $this->url('forschung', array('action' => 'index')); ?>"
           class="ajaxButton closeButton btn btn-medium" id="closebutton">
            "Hier schliessen"
        </a>
    </div>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo  $this->ztbFlashMessenger()->render() ?>

<div class="tabbable">
    <ul class="nav nav-tabs formTabs">
        <li class="active"><a href="#forschungsarbeiten"><?php echo  $this->translate('Forschungsarbeiten ', 'Libadmin') ?></a></li>
        <li><a href="#medien"><?php echo  $this->translate('Medien', 'Libadmin') ?></a></li>
        <li><a href="#zoradocs"><?php echo  $this->translate('Zora Docs', 'Libadmin') ?></a></li>
    </ul>


    <div class="tab-content">
        <div class="tab-pane active" id="forschungsarbeiten">
            <fieldset class="general">
                <legend><?php echo  $this->translate('Liste der Forschungsarbeiten ','Libadmin') ?></legend>
                    <?php foreach ($forschungsarbeiten as $forschung) :?>
                        <div class="row-fluid">
                            <div class="span6">
                                <?php echo  $this->formRowTwb($forschung->get('qarb_arb_id')); ?>
                            </div>
                            <div class="span6">
                                <?php echo  $this->formRowTwb($forschung->get('qarb_arb_titel')); ?>
                            </div>
                        </div>

                    <?php endforeach; ?>

            </fieldset>



        </div>


        <div class="tab-pane" id="medien">

            <fieldset class="general">
                <legend><?php echo  $this->translate('Liste der Medien ','Libadmin') ?></legend>
                <?php foreach ($medien as $medium) :?>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php echo  $this->formRowTwb($medium->get('id')); ?>
                        </div>
                        <div class="span6">
                            <?php echo  $this->formRowTwb($medium->get('gespraechstitel')); ?>
                        </div>
                    </div>

                <?php endforeach; ?>

            </fieldset>


        </div>

        <div class="tab-pane" id="zoradocs">

            <fieldset class="general">
                <legend><?php echo  $this->translate('Liste der Zoraarbeiten ','Libadmin') ?></legend>
                <?php foreach ($zoradocs as $zoradoc) :?>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php echo  $this->formRowTwb($zoradoc->get('title')); ?>
                        </div>
                        <div class="span6">
                            <?php $identifier = $zoradoc->get('oai_identifier')->getValue();
                            $matches = array();

                            $grepresult =  preg_match('/oai:www\.zora\.uzh\.ch:(\d+)$/',$identifier,$matches);
                            ?>
                            <a  target="_blank" href='<?php echo   'http://www.zora.uzh.ch/' .   $matches[1] ?>'>Link zu Zora</a>
                        </div>
                    </div>

                <?php endforeach; ?>

            </fieldset>


        </div>




</div>


<?php echo  $this->form()->closeTag(); ?>