<?php


$this->headTitle("Forschungsarbeiten");


$form = $this->form;

$form->setAttribute('action', $this->url(
    'forschung',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();


$lizz_master = $form->get('lizentiatmaster');
$dissertations = $form->get('dissertation');


$saveButtonLabel = "Speichern";

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formLabel()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

?>



<?= $this->formTwb()->openTag($form, $formType) ?>
    <div class="topButtons">
        <input type="submit" value="<?= $this->escapeHtml($saveButtonLabel) ?>"
               class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
        <a href="<?= $this->url('forschung', array('action' => 'index')); ?>"
           class="ajaxButton closeButton btn btn-medium" id="closebutton">
            "Hier schliessen"
        </a>
    </div>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?= $this->ztbFlashMessenger()->render() ?>

<div class="tabbable">
    <ul class="nav nav-tabs formTabs">
        <li class="active">
            <a href="#lizentiate_masters"><?= $this->translate('Lizentiate_masters ', 'Libadmin') ?></a>
        </li>
        <li><a href="#dissertations"><?= $this->translate('dissertations', 'Libadmin') ?></a></li>
    </ul>


    <div class="tab-content">
        <div class="tab-pane active" id="lizentiate_masters">
            <fieldset>
                <legend>lizz / master arbeiten</legend>

                    <?php foreach ($lizz_master as $singlelizzmaster) :?>
                        <div class="row-fluid">
                            <div class="span6">
                               <?= $singlelizzmaster?>
                            </div>
                            <div class="span6">
                                test 2
                            </div>
                        </div>

                    <?php endforeach; ?>

            </fieldset>

        </div>
    </div>

    <div class="tab-content">
        <div class="tab-pane" id="dissertations">
            <fieldset>
                <legend>Dissertationen</legend>

                    <?php foreach ($dissertations as $dissertation) :?>
                        <div class="row-fluid">
                            <div class="span6">
                                <?= $this->formRowTwb($dissertation->get('qarb_arb_autorid')) ?>
                            </div>
                            <div class="span6">
                                <?= $this->formRowTwb($dissertation->get('qarb_arb_titel')) ?>
                            </div>
                        </div>

                    <?php endforeach; ?>


            </fieldset>
        </div>
    </div>


</div>


<?= $this->form()->closeTag(); ?>