<?php


$this->headTitle("Forschungsarbeiten");


$form = $this->form;

$form->setAttribute('action', $this->url(
    'forschungAdmin',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();


$lizz_master = $form->get('lizentiatmaster');
$dissertations = $form->get('dissertation');
$habil = $form->get('habilitation');



$saveButtonLabel = "Speichern";

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formLabel()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

?>



<?php echo $this->formTwb()->openTag($form, $formType) ?>
    <div class="topButtons">
        <input type="submit" value="<?php echo $this->escapeHtml($saveButtonLabel) ?>"
               class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
        <a href="<?php echo $this->url('forschungAdmin', array('action' => 'index')); ?>"
           class="ajaxButton closeButton btn btn-medium" id="closebutton">
            "Hier schliessen"
        </a>
    </div>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo $this->ztbFlashMessenger()->render() ?>

<div class="tabbable">
    <ul class="nav nav-tabs formTabs">
        <li class="active"><a href="#lizentiate_masters"><?php echo $this->translate('Lizentiate_masters ', 'Libadmin') ?></a></li>
        <li><a href="#dissertations"><?php echo $this->translate('dissertations', 'Libadmin') ?></a></li>
        <li><a href="#habil"><?php echo $this->translate('Habilitationen', 'Libadmin') ?></a></li>
    </ul>


    <div class="tab-content">
        <div class="tab-pane active" id="lizentiate_masters">
            <?php echo $this->render('fsw/global/forschungen', array('forschungen' => $lizz_master,
                                                                'legende' => 'lizz master arbeiten')); ?>
        </div>
        <div class="tab-pane" id="dissertations">
                <?php echo $this->render('fsw/global/forschungen', array('forschungen' => $dissertations,
                    'legende' => 'dissertations')); ?>
        </div>

        <div class="tab-pane" id="habil">
            <?php echo $this->render('fsw/global/forschungen', array('forschungen' => $habil,
                'legende' => 'Habilitationen')); ?>
        </div>
    </div>


</div>


<?php echo $this->form()->closeTag(); ?>