<?php

$title = 'Add new Medium';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('fsw', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('medienid'));
echo $this->formRow($form->get('gespraechstitel'));
echo $this->formRow($form->get('sendetitel'));
echo $this->formRow($form->get('mit_id'));
echo $this->formRow($form->get('icon'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();