<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />


        <?php	// Styles



        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))

            ->prependStylesheet($this->basePath() . '/html/css/cmsIFrameFSW.css')
            ->prependStylesheet($this->basePath() . '/html/css/uzh.css')

        ?>

        <?php	// Scripts
        $this->headScript()

            ->prependFile($this->basePath() . '/js/jquery.js')
            ->appendFile($this->basePath() . '/html/js/fsw.js');

        echo $this->headScript();
        ?>

        <!-- Le styles -->

        

    </head>
    <body>
        <div class="bodywidthIFrame">
            <?php echo $this->content; ?>

        </div>

    </body>
</html>
