

<?php
    $kolloquien = $this->kolloquienWithDpendencies;
?>



<?php foreach ($kolloquien as $kolloquium): ?>

<div class="objectContainer" >


    <h2><?php echo $kolloquium->getTitel();  ?></h2>

    <div >
        <a class="internal abstractCaption" href="#">mehr</a>
        <p> &nbsp;</p>


        <?php foreach ($kolloquium->getVeranstaltung() as $veranstaltung): ?>
            <?php foreach ($veranstaltung->getVortragend() as $vortragend): ?>

                <?php if ($vortragend->getPerson_link() != null && strlen($vortragend->getPerson_link()) > 0): ?>
                    <span><a class="internal" target="_blank" href="<?php echo $vortragend->getPerson_link() ?>">
                            <?php echo $vortragend->getVor_name(); ?> &nbsp; <?php echo $vortragend->getNach_name(); ?></a></span>
                <?php else: ?>
                    <span><?php echo $vortragend->getVor_name(); ?> &nbsp; <?php echo $vortragend->getNach_name(); ?></span>

                <?php endif; ?>


            <?php endforeach; ?>

            <?php $index = 0; ?>
            <?php foreach ($veranstaltung->getVortragend() as $vortragend): ?>

                <?php if ($index == 0): ?>
                    <?php if ($vortragend->getInstitution_link_bild() != null && strlen($vortragend->getInstitution_link_bild()) > 0): ?>
                        <span><a class="internal" target="_blank" href="<?php echo $vortragend->getInstitution_link_bild() ?>">
                        <?php echo $vortragend->getInstitution_name(); ?></a></span>
                    <?php else: ?>
                        <span><?php echo $vortragend->getInstitution_name(); ?></span>
                    <?php endif; ?>
                <?php endif; ?>

                <?php $index++; ?>
            <?php endforeach; ?>


            <p><strong><?php $veranstaltung->getVeranstaltung_titel(); ?>&nbsp;&nbsp;(<?php echo $this->date( $veranstaltung->getDatum(),'long')  ?> )</strong></p>

            <?php foreach ($veranstaltung->getVortragend() as $vortragend): ?>

                <?php if ($vortragend->getPersoneninformation() != null && strlen($vortragend->getPersoneninformation()) > 0): ?>
                    <div class="vortragende">
                        <a class="internal abstractCaptionChild" href="#">mehr zu Personen</a>
                        <div class="abstractTextChild">
                            <?php echo $vortragend->getPersoneninformation(); ?>

                        </div>
                    </div>

                <?php endif; ?>

            <?php endforeach; ?>

            <?php if ($veranstaltung->getBeschreibung() != null && strlen($veranstaltung->getBeschreibung()) > 0): ?>
                <p><?php echo $veranstaltung->getBeschreibung(); ?></p>
            <?php endif; ?>


            <br/>


        <?php endforeach; ?>

    </div>

</div>

<?php endforeach; ?>



