

<?php
    $kolloquien = $this->kolloquienWithDpendencies;
?>



<?php foreach ($kolloquien as $kolloquium): ?>

<div class="skin-text-basics objectContainer" >


    <h2><?php echo $kolloquium->getTitel();  ?></h2>

    <div >
        <a class="internal abstractCaption" href="#">mehr</a>
        <p> &nbsp;</p>

        <div class="abstractText veranstaltungen">
        <?php foreach ($kolloquium->getVeranstaltung() as $veranstaltung): ?>
            <?php foreach ($veranstaltung->getVortragend() as $vortragend): ?>

                <?php
                    //Personenlink soll nicht mehr angezeigt werden - Wunsch Manuela 4.2.2015
                    echo '<span>' . $vortragend->getVor_name() . '&nbsp;' .  $vortragend->getNach_name() . '</span>';
                ?>


            <?php endforeach; ?>

            <?php $index = 0; ?>
            <?php foreach ($veranstaltung->getVortragend() as $vortragend): ?>

                <?php if ($index == 0): ?>

                    <?php
                    if ($vortragend->getInstitution_link() != null && strlen($vortragend->getInstitution_link()) > 0) {
                        echo '<span>' . $this->internalExternalLink()->createLink($vortragend->getInstitution_link(),
                                $vortragend->getInstitution_name() . '</span>');
                    } else {
                        echo '<span>' . $vortragend->getInstitution_name() . '</span>';
                    }
                    ?>
                <?php endif; ?>

                <?php $index++; ?>
            <?php endforeach; ?>


            <p><strong><?php echo $veranstaltung->getVeranstaltung_titel(); ?>&nbsp;&nbsp;(<?php echo $this->date( $veranstaltung->getDatum(),'dateonly')  ?>)</strong></p>

            <?php foreach ($veranstaltung->getVortragend() as $vortragend): ?>

                <?php if ($vortragend->getPersoneninformation() != null && strlen($vortragend->getPersoneninformation()) > 0): ?>
                    <div class="vortragende">
                        <a class="internal abstractCaptionChild" href="#">mehr zu Personen</a>
                        <div class="abstractTextChild">
                            <?php echo $vortragend->getPersoneninformation(); ?>

                        </div>
                    </div>

                <?php endif; ?>

            <?php endforeach; ?>

            <?php if ($veranstaltung->getBeschreibung() != null && strlen($veranstaltung->getBeschreibung()) > 0): ?>
                <p><?php echo $veranstaltung->getBeschreibung(); ?></p>
            <?php endif; ?>


            <br/>


        <?php endforeach; ?>

    </div>

</div>

<?php endforeach; ?>



