
<?php


    $form = $this->form;


    $form->prepare();

    $vortragend = $form->get('vortragend');


?>
<?php echo  $this->formTwb()->openTag($form, 'horizontal') ?>

<fieldset>
    <legend>Person</legend>
    <?php echo $this->ztbFlashMessenger()->render() ?>
    <div class="row-fluid">
        <div class="span6">
            <?php echo  $this->formRowTwb($vortragend->get('id')) ?>
        </div>

        <div class="span6">
            <?php echo  $this->formRowTwb($vortragend->get('id_kolloquium_veranstaltung')) ?>
        </div>

    </div>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('nach_name')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('vor_name')) ?>
            </div>

        </div>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('personeninformation')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('person_link')) ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_name')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_link')) ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_link_bild')) ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('id_personen_extended')) ?>
            </div>




        </div>

</fieldset>

<?php echo  $this->form()->closeTag(); ?>
