
<?php
    $form = $this->form;
    $form->prepare();

    $form->setAttribute('action', $this->url(
        'kolloquien',
        array(
            'action' => 'editVeranstaltung',
            'id'     => $this->id,
        )
    ));
    $kolloquium = $form->getBaseFieldset();



?>
<?php echo  $this->formTwb()->openTag($form, 'horizontal') ?>

<fieldset>

    <legend><?php echo isset($this->update) && $this->update === True && count($form->getMessages()) == 0 ? "update der Kolloquiumsdatendaten erfolgreich" : "Kolloquiumsattribute"  ?></legend>

    <fieldset>
        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($kolloquium->get('id')) ?>
            </div>
            <div class="span6">
                <?php echo  $this->formRowTwb($kolloquium->get('id_kolloquium')) ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($kolloquium->get('titel')) ?>
            </div>
        </div>
    </fieldset>


</fieldset>

<?php echo  $this->form()->closeTag(); ?>
