<?php


$this->headTitle("Dies ist ein Kolloqium");


$form = $this->form;

$form->setAttribute('action', $this->url(
    'kolloquien',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();

$kolloquium = $form->get('Kolloqium');

$veranstaltungen = $kolloquium->get('veranstaltung');

foreach ($veranstaltungen as $veranstaltung) {

   $person = $veranstaltung->get('vortragend');

}





$saveButtonLabel = "Speichern";

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formLabel()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

?>



<?php echo  $this->formTwb()->openTag($form, $formType) ?>
    <div class="topButtons">
        <a href="#"  class="btn btn-medium" id="addKolloqiumButton">add new Kolloquium</a>
        <a href="#"  class="btn btn-medium" id="updateKolloqiumButton">update Kolloquium</a>
        <a href="#"  class="btn btn-medium" id="deleteKolloqiumButton">delete Kolloquium</a>
    </div>

    <h3><?php echo $this->escapeHtml($title); ?></h3>

<?php echo  $this->ztbFlashMessenger()->render() ?>

    <div class="tabbable">
        <ul class="nav nav-tabs formTabs">
            <li class="active">
                <a href="#kolloquiumPane"><?php echo  $this->translate('Kolloquium Atrribute', 'Libadmin') ?></a>
            </li>
            <li><a href="#veranstaltungen"><?php echo  $this->translate('veranstaltungen Kolloquium', 'Libadmin') ?></a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="kolloquiumPane">

                <fieldset>
                    <legend>Kolloquiumatribute</legend>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php echo  $this->formRowTwb($kolloquium->get('id')) ?>
                        </div>
                        <div class="span6">
                            <?php echo  $this->formRowTwb($kolloquium->get('id_kolloquium')) ?>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php echo  $this->formRowTwb($kolloquium->get('titel')) ?>
                        </div>
                    </div>
                </fieldset>


            </div>
            <div class="tab-pane" id="veranstaltungen">
                <fieldset>
                    <legend>Veranstaltungen zum Kolloquium</legend>

                        <?php $numberVeranstaltung = 0 ?>
                        <?php foreach ($veranstaltungen as $veranstaltung) :?>
                            <?php if ($numberVeranstaltung != 0) : ?>
                                <div>=======================</div>
                            <?php endif;  ?>


                            <div class="row-fluid">
                                <div class="span6">
                                    <?php echo  $this->formRowTwb($veranstaltung->get('id')) ?>
                                </div>
                                <div class="span6">
                                    <?php echo  $this->formRowTwb($veranstaltung->get('id_kolloquium')) ?>
                                </div>
                            </div>

                            <div class="row-fluid">
                                <div class="span6">
                                    <?php echo  $this->formRowTwb($veranstaltung->get('datum')) ?>
                                </div>
                                <div class="span6">
                                    <?php echo  $this->formRowTwb($veranstaltung->get('veranstaltung_titel')) ?>
                                </div>
                            </div>

                            <div class="row-fluid">
                                <div class="span6">
                                    <?php echo  $this->formRowTwb($veranstaltung->get('beschreibung')) ?>
                                </div>
                            </div>


                                <?php foreach ( $veranstaltung->get('vortragend') as $vortragend) :?>

                                <div class="row-fluid">
                                    <div class="span6">
                                        <?php echo  $this->formRowTwb($vortragend->get('nach_name')) ?>
                                    </div>
                                </div>

                                <?php endforeach; ?>


                            <div class="row-fluid">
                            <div class="span2" style="margin-right: 10px;">
                                <a href="#"
                                   class="showPersonenVeranstaltung" veranstaltungID="<?php echo $veranstaltung->get('id')->getValue(); ?>">zeige Personen zur Veranstaltung</a>
                            </div>
                            </div>



                            <?php $numberVeranstaltung++; ?>
                        <?php endforeach; ?>

                </fieldset>

            </div>


        </div>
    </div>

<?php echo  $this->form()->closeTag(); ?>