
<?php

        $this->headTitle("Dies ist eine Veranstaltung");

    $form = $this->form;


    $form->prepare();

    $veranstaltung = $form->get('Veranstaltungen');

    $vortragende = $veranstaltung->get('vortragend');

?>
<?php echo  $this->formTwb()->openTag($form, 'horizontal');

?>

<script language="JavaScript"   >
    $(".deleteCurrentPersonLink").on('click', function (e) {

        e.preventDefault();

        var currentPersonNumber = $(e.target).attr('data-PersonId');

        $("#fswDialogBox").load('/static/zf2/public/index.php/kolloquien/deletePersonVeranstaltung/' + currentPersonNumber);


    });



    $(".updateCurrentPersonLink").on('click', function (e) {


        e.preventDefault();
        var currentIndexId = $(e.target).attr('data-currentIndex');

        var currentPersonNumber = $(e.target).attr('data-PersonId');


        var nach_name = $('#Veranstaltungen\\[vortragend\\]\\[' +  currentIndexId  +  '\\]\\[nach_name\\]').val();
        var vor_name = $('#Veranstaltungen\\[vortragend\\]\\[' +  currentIndexId  +  '\\]\\[vor_name\\]').val();
        var person_link = $('#Veranstaltungen\\[vortragend\\]\\[' +  currentIndexId  +  '\\]\\[person_link\\]').val();
        var institution_name = $('#Veranstaltungen\\[vortragend\\]\\[' +  currentIndexId  +  '\\]\\[institution_name\\]').val();
        var institution_link = $('#Veranstaltungen\\[vortragend\\]\\[' +  currentIndexId  +  '\\]\\[institution_link\\]').val();
        var institution_link_bild = $('#Veranstaltungen\\[vortragend\\]\\[' +  currentIndexId  +  '\\]\\[institution_link_bild\\]').val();
        var personeninformation = $('#Veranstaltungen\\[vortragend\\]\\[' +  currentIndexId  +  '\\]\\[personeninformation\\]').val();


        $("#fswDialogBox").load('/static/zf2/public/index.php/kolloquien/updatePersonVeranstaltung/' + currentPersonNumber,

            {
                'nach_name' : nach_name,
                'vor_name'  : vor_name,
                'person_link'   : person_link,
                'institution_link'  : institution_link,
                'institution_name'  : institution_name,
                'institution_link_bild' : institution_link_bild,
                'personeninformation'   : personeninformation

            }
        );


    })



</script



<fieldset>
    <legend>Personen</legend>
    <?php echo $this->ztbFlashMessenger()->render() ?>
    <?php $numberPerson = 0 ?>

    <?php foreach ( $veranstaltung->get('vortragend') as $vortragend) :?>

        <?php if ($numberPerson != 0) : ?>
            <div class="row-fluid">
                <div>==========================================================================================</div>
            </div>
        <?php endif;  ?>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('id')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('id_kolloquium_veranstaltung')) ?>
            </div>

        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('nach_name')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('vor_name')) ?>
            </div>

        </div>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('personeninformation')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('person_link')) ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_name')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_link')) ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_link_bild')) ?>
            </div>
        </div>


        <div class="row-fluid">
            <div class="span2" style="margin-left: 30px;">
                <a href="#"
                   class="deleteCurrentPersonLink" data-currentIndex="<?php echo $numberPerson; ?>" data-PersonId="<?php echo $vortragend->get('id')->getValue(); ?>">delete Person</a>
            </div>

            <div class="span2" style="margin-left: 30px;">
                <a href="#"
                   class="updateCurrentPersonLink" data-currentIndex="<?php echo $numberPerson; ?>" data-PersonId="<?php echo $vortragend->get('id')->getValue(); ?>">update Person</a>
            </div>

        </div>

        <?php $numberPerson++; ?>
    <?php endforeach; ?>
</fieldset>

<?php echo  $this->form()->closeTag(); ?>

