
<?php

        $this->headTitle("Dies ist eine Veranstaltung");

    $form = $this->form;


    $form->prepare();

    $veranstaltung = $form->get('Veranstaltungen');

    $vortragende = $veranstaltung->get('vortragend');

?>
<?php echo  $this->formTwb()->openTag($form, 'horizontal') ?>

<fieldset>
    <legend>Personen</legend>
    <?php foreach ( $veranstaltung->get('vortragend') as $vortragend) :?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('nach_name')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('vor_name')) ?>
            </div>

        </div>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('personeninformation')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('person_link')) ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_name')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_link')) ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_link_bild')) ?>
            </div>


        </div>

    <?php endforeach; ?>
</fieldset>

<?php echo  $this->form()->closeTag(); ?>
