
<?php

        $this->headTitle("Dies ist eine Veranstaltung");

    $form = $this->form;


    $form->prepare();

    $veranstaltung = $form->get('Veranstaltungen');

    $vortragende = $veranstaltung->get('vortragend');

?>
<?php echo  $this->formTwb()->openTag($form, 'horizontal') ?>

<fieldset>
    <legend>Personen</legend>

    <?php $numberPerson = 0 ?>

    <?php foreach ( $veranstaltung->get('vortragend') as $vortragend) :?>

        <?php if ($numberPerson != 0) : ?>
            <div class="row-fluid">
                <div>==========================================================================================</div>
            </div>
        <?php endif;  ?>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('id')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('id_kolloquium_veranstaltung')) ?>
            </div>

        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('nach_name')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('vor_name')) ?>
            </div>

        </div>


        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('personeninformation')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('person_link')) ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_name')) ?>
            </div>

            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_link')) ?>
            </div>

        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($vortragend->get('institution_link_bild')) ?>
            </div>
        </div>


        <div class="row-fluid">
            <div class="span2" style="margin-left: 30px;">
                <a href="#"
                   class="deleteCurrentPersonButton" data-currentIndex="<?php echo $numberPerson; ?>">delete Veranstaltung</a>
            </div>
        </div>

        <?php $numberPerson++; ?>
    <?php endforeach; ?>
</fieldset>

<?php echo  $this->form()->closeTag(); ?>

<script language="JavaScript">

    $('.deleteCurrentPersonButton').on('click',function(event){

        event.preventDefault();
        var currentPersonIndex = $(event.target).attr('data-currentindex');

        $('#fswDialogBox').attr('data-dialogAttr');

        $('<div id="okEscDialog" title="Loeschen einer Person">' +
        '<p>Wollen Sie die Person</p>' +
        '<p>loeschen?</p>' +
        '</div>')
            .dialog({
                buttons: [
                    {
                        text: "OK",
                        click: function(event) {


                            var currentVortragendID = $('#Veranstaltungen\\[vortragend\\]\\['  +  currentPersonIndex  +   '\\]\\[id\\]').val();

                            $('#fswDialogBox').load('/kolloquien/deletePersonVeranstaltung/' + currentVortragendID).css('background-color','#d9d9d9');
                            $( this ).dialog( "close" );

                        }

                    },
                    {
                        text: "Abbrechen",
                        click: function() {
                            $( this ).dialog( "close" );
                        }
                    }

                ],
                open: function(){

                    $('#okEscDialog').css('background-color','#149bdf');
                },
                close: function (event, ui) {
                    $(this).dialog('destroy').remove();
                }

            }).dialog( "widget")
            .find( ".ui-dialog-titlebar-close" )
            .hide();

    });


</script>
