<?php


$this->headTitle("Dies ist ein Kolloqium");


$form = $this->form;

$form->setAttribute('action', $this->url(
    'kolloquien',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();

$kolloquium = $form->get('Kolloqium');



$saveButtonLabel = "Speichern";

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formLabel()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

?>



<?php echo  $this->formTwb()->openTag($form, $formType) ?>
    <div class="topButtons">
        <input type="submit" value="<?php echo  $this->escapeHtml($saveButtonLabel) ?>"
               class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
        <a href="<?php echo  $this->url('kolloquien', array('action' => 'index')); ?>"
           class="ajaxButton closeButton btn btn-medium" id="closebutton">
            "passiert hier etwas?"
        </a>
    </div>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo  $this->ztbFlashMessenger()->render() ?>

    <div class="tabbable">
        <ul class="nav nav-tabs formTabs">
            <li class="active">
                <a href="#kolloquium"><?php echo  $this->translate('Kolloquium Atrribute', 'Libadmin') ?></a>
            </li>
            <li><a href="#veranstaltungen"><?php echo  $this->translate('veranstaltungen Kolloquium', 'Libadmin') ?></a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="kolloquium">

                <fieldset>
                    <legend>Kolloquiumatribute</legend>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php echo  $this->formRowTwb($kolloquium->get('id')) ?>
                        </div>
                        <div class="span6">
                            <?php echo  $this->formRowTwb($kolloquium->get('id_kolloquium')) ?>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <?php echo  $this->formRowTwb($kolloquium->get('titel')) ?>
                        </div>
                    </div>
                </fieldset>


            </div>
            <div class="tab-pane" id="veranstaltungen">
                <fieldset>
                    <legend>hier kommen die Veranstaltungen hin</legend>



                </fieldset>

            </div>


        </div>
    </div>

<?php echo  $this->form()->closeTag(); ?>