<?php if (isset($complete) && $complete): ?>

    <div class="row">
        <div class="span3" id="sidebar">
            <?php echo
            $this->render('fsw/global/sidebar', array(
                'route' => 'kolloquien',
                'listItems' => $kolloquien
            ));?>
        </div>
        <div class="span9" id="content">
            <?php echo $this->render('fsw/kolloquien/edit_template', array(

                    'form' => $this->form,
                    'title' => $this->translate('kolloquien_edit', 'FSW'),

                )
            );
            ?>
        </div>
    </div>

<?php else: ?>

    <?php echo $this->render('fsw/kolloquien/edit_template', array(

            'form' => $this->form,
            'title' => $this->translate('kolloquien_edit', 'FSW'),

        )
    ); ?>


<?php endif; ?>


