

<?php
    //$formFromUntil = $this->formFromUntil;
    $formFromUntil->prepare();
    $fieldsetFromUntil = $formFromUntil->getBaseFieldset();
    $formFromUntil->setAttribute('action',$this->url('harvest',array('action' => 'harvestFromUntil')));

    ?>


<?php echo  $this->formTwb()->openTag($formFromUntil, 'horizontal') ?>


<fieldset class="edit_legend_title_medien">
    <legend>1. Möglichkeit Zora Dokumente zu harvesten: from  / until</legend>
</fieldset>

<fieldset class="general">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span4"><?php echo  $this->formRowTwb($fieldsetFromUntil->get('from')) ?></div>
            <div class="span6">Format: yyyy-mm-dd [mandatory]</div>
        </div>
        <div class="row-fluid">
            <div class="span4"><?php echo  $this->formRowTwb($fieldsetFromUntil->get('until')) ?></div>
            <div class="span6">Format: yyyy-mm-dd [optional]</div>
        </div>
        <div class="row-fluid">
            <div class="span12"><?php echo  $this->formRowTwb($fieldsetFromUntil->get('submitFromUntil')) ?></div>
        </div>

    </div>
</fieldset>
<?php echo  $this->form()->closeTag(); ?>



<?php
//$formFromUntil = $this->formFromUntil;
$formEntities->prepare();
$fieldsetEntities = $formEntities->getBaseFieldset();
$formEntities->setAttribute('action',$this->url('harvest',array('action' => 'harvestEntities')));

?>


<?php echo  $this->formTwb()->openTag($formEntities, 'horizontal') ?>


<fieldset class="edit_legend_title_medien">
    <legend>2. Möglichkeit Zora Dokumente zu harvesten: Angabe einzelner entities</legend>
</fieldset>

<fieldset class="general">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span10"><?php echo  $this->formRowTwb($fieldsetEntities->get('entities')) ?></div>
        </div>
            <div class="span4 abstandLeft">Format:&nbsp;oai:www.zora.uzh.ch:13498##oai:www.zora.uzh.ch:13509</div>
        <div class="row-fluid">
            <div class="span12"><?php echo  $this->formRowTwb($fieldsetEntities->get('submitEntities')) ?></div>
        </div>

    </div>
</fieldset>
<?php echo  $this->form()->closeTag(); ?>


<?php if (isset($this->messages) && is_array($this->messages) && count($this->messages) > 0): ?>

    <div class="row-fluid">
    <?php foreach ($this->messages as $message): ?>

        <div><?php echo $message;  ?></div>


    <?php endforeach; ?>
    </div>


    <?php endif; ?>


