

<?php
    $semesterArray = $this->lvWithDpendencies;
?>



<div id="tabs" >

    <ul>

        <?php foreach($this->archivLabels as $key => $value): ?>
            <li><a href="#tab-<?php echo $key; ?>"><?php echo $value ?></a></li>

        <?php endforeach; ?>
    </ul>
    <?php foreach($semesterArray as $semesterKey => $lehrVeranstaltungenImSemester): ?>

        <div id="tab-<?php echo $semesterKey?>" class="tab">
        <ul    class="type1">

        <?php foreach($lehrVeranstaltungenImSemester as $lv): ?>
            <li class="marginTop ">
                <div class="noMarginBottom">
                    <?php if (!is_null($lv->getVvzlink()) && strlen($lv->getVvzlink()) > 0): ?>
                        <a class="internal"   href="<?php echo $lv->getVvzlink(); ?>" target="_blank"><?php echo $lv->getTitel(); ?></a>
                    <?php else: ?>
                        <strong><?php echo $lv->getTitel();  ?></strong>
                    <?php endif; ?>


                    <?php
                    $i = 0;
                    $numberPersons = count($lv->getPersonenInfo());
                    ?>

                    <?php if ($numberPersons > 0): ?>


                        <?php foreach ($lv->getPersonenInfo() as $pi): ?>

                            <?php if (!is_null($a = $pi->getProfilURL()) && strlen($pi->getProfilURL()) > 0): ?>
                                <a class="internal displayParent" href="<?php echo $pi->getProfilURL(); ?>">
                                    <?php echo trim($pi->getNachName()) . ", " . trim($pi->getVorName()); ?>
                                </a>
                            <?php else: ?>
                                <?php echo trim($pi->getNachName()) . ", " . trim($pi->getVorName()); ?>
                            <?php endif; ?>
                            <?php $i++; ?>
                            <?php if ($i < $numberPersons): ?>&nbsp;<?php endif; ?>

                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

                <?php echo $lvLabels[$lv->getSemester()] ; ?>

                <?php if ((!is_null($lv->getBeschreibung()) && strlen($lv->getBeschreibung()) > 0)
                    && (is_null($lv->getVvzlink()) || strlen($lv->getVvzlink() == 0) )): ?>


                    <div>
                        <a class="internal abstractCaption" href="#">mehr</a>

                        <div class="abstractText">
                            <?php echo $lv->getBeschreibung(); ?>
                        </div>


                    </div>

                <?php endif; ?>

                <p>&nbsp;</p>


            </li>

        <?php endforeach;?>
        </ul>

        </div>

    <?php endforeach; ?>



</div>


