

<?php
    $semesterArray = $this->lvWithDpendencies;
?>



<div id="tabs" >

    <ul>

        <?php foreach($this->archivLabels as $key => $value): ?>
            <li><a href="#tab-<?php echo $key; ?>"><?php echo $value ?></a></li>

        <?php endforeach; ?>
    </ul>
    <?php foreach($semesterArray as $semesterKey => $lehrVeranstaltungenImSemester): ?>

        <div id="tab-<?php echo $semesterKey?>" class="tab">
        <ul    class="type1">

        <?php foreach($lehrVeranstaltungenImSemester as $lv): ?>
            <li class="marginTop ">
                <div >

                    <?php
                    if (!is_null($lv->getVvzlink()) && strlen($lv->getVvzlink()) > 0) {
                        echo $this->internalExternalLink()->createLink($lv->getVvzlink(), $lv->getTitel());
                    } else {

                        echo '<b>' . $lv->getTitel() . '</b>';
                    }

                    ?>

                    <?php
                    $i = 0;
                    $numberPersons = count($lv->getPersonenInfo());
                    ?>

                    <?php if ($numberPersons > 0): ?>


                        <?php foreach ($lv->getPersonenInfo() as $pi): ?>

                            <?php
                            if (!is_null($a = $pi->getProfilURL()) && strlen($pi->getProfilURL()) > 0) {
                                echo $this->internalExternalLink()->createLink($pi->getProfilURL(), trim($pi->getNachName()) . ", " . trim($pi->getVorName()));
                            } else {
                                echo trim($pi->getNachName()) . ", " . trim($pi->getVorName());
                            }
                            ?>

                            <?php $i++; ?>
                            <?php if ($i < $numberPersons): ?>&nbsp;<?php endif; ?>

                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>



                <?php if ((!is_null($lv->getBeschreibung()) && strlen($lv->getBeschreibung()) > 0)
                    && (is_null($lv->getVvzlink()) || strlen($lv->getVvzlink() == 0) )): ?>


                    <div>
                        <a class="internal abstractCaption" href="#">mehr</a>

                        <div class="abstractText">
                            <?php echo $lv->getBeschreibung(); ?>
                        </div>


                    </div>

                <?php endif; ?>


            </li>

        <?php endforeach;?>
        </ul>

        </div>

    <?php endforeach; ?>



</div>


