

<?php
    $semesterArray = $this->lvWithDpendencies;
?>



<ul class="type1">
    <?php foreach($semesterArray as $semesterKey => $lehrVeranstaltungenImSemester): ?>
        <?php foreach($lehrVeranstaltungenImSemester as $lv): ?>
            <li>
                <?php
                $i = 0;
                $numberPersons = count($lv->getPersonenInfo());
                ?>

                <?php foreach ($lv->getPersonenInfo() as $pi): ?>
                    <div>
                        <?php if (!is_null($a = $pi->getProfilURL()) && strlen($pi->getProfilURL()) > 0): ?>
                            <a class="internal displayParent" href="<?php echo $pi->getProfilURL(); ?>">
                                <?php echo $pi->getNachName() . " " . $pi->getVorName(); ?>
                            </a>
                        <?php else: ?>
                            <?php echo $pi->getNachName() . " " . $pi->getVorName(); ?>
                        <?php endif; ?>


                    <?php $i++; ?>
                    <?php if ($i < $numberPersons): ?>
                    ,
                    <?php endif; ?>
                       &nbsp;
                <?php endforeach; ?>
                <?php if (!is_null($lv->getVvzlink()) && strlen($lv->getVvzlink()) > 0): ?>
                    <p><a class="internal"   href="<?php echo $lv->getVvzlink(); ?>" target="_blank"><?php echo $lv->getTitel(); ?></a></p>
                <?php else: ?>
                    <strong><?php echo $lv->getTitel();  ?></strong>
                <?php endif; ?>


                <?php if (!is_null($lv->getOlatlink()) && strlen($lv->getOlatlink()) > 0): ?>
                    <p><a class="internal"   href="<?php echo $lv->getOlatlink(); ?>" target="_blank">OLAT</a></p>
                <?php endif; ?>
                    </div>

                <?php if ((!is_null($lv->getBeschreibung()) && strlen($lv->getBeschreibung()) > 0)
                    && (is_null($lv->getVvzlink()) || strlen($lv->getVvzlink() == 0) )): ?>


                    <div>
                        <a class="internal abstractCaption" href="#">mehr</a>

                        <div class="abstractText">
                            <?php echo $lv->getBeschreibung(); ?>
                        </div>


                    </div>

                <?php endif; ?>


            </li>
        <?php endforeach; ?>
    <?php endforeach; ?>
</ul>


