

<?php
    $medien = $this->medien;
?>



<?php foreach ($medien as $medium): ?>

<div class="skin-text-basics objectContainer" >

    <!--<div class="objectFloat left" style="width:80px;" > -->
    <div  style="width:80px;" >
    <img src="<?php echo "http://www.fsw.uzh.ch/static/img/" . $medium->getIcon(); ?>" />
    </div>
    <br/>
    <?php
        $numberPersons = count($medium->getPersonenInfo());
    ?>


    <?php if ($numberPersons > 0): ?>


        <?php foreach ($medium->getPersonenInfo() as $pi): ?>

            <?php
            if (!is_null($a = $pi->getProfilURL()) && strlen($pi->getProfilURL()) > 0) {

                echo $this->internalExternalLink()->createLink($pi->getProfilURL(),trim($pi->getNachName())  . ", " . trim($pi->getVorName() . "." )) ;
            } else {
                echo trim($pi->getNachName()) . ", " . trim($pi->getVorName());
            }

            ?>

        <?php endforeach; ?>
    <?php endif; ?>




    <?php $date = new DateTime($medium->getDatum()); ?>
    <?php echo $medium->getSendetitel() ?>  vom  <?php echo $date->format('d.m.Y') ?>
    <br />
    <?php echo $this->internalExternalLink()->createLink($medium->getLink(),$medium->getGespraechstitel());  ?>

    <br style="margin-bottom: 0px" class="floatclear" />

</div>

<?php endforeach; ?>



