<?php


//edit-zora-author kann auch im Kontext von z.B. edit (Personen) aufgerufen werden
//->dann wenn die Daten einer Person komplett zum erste Mal im Editor - Bereich der Oberfläche ngezeigt werden
if (!isset($formPrepared) || $formPrepared == false) {
    $form->prepare();
}

$personCore = $form->get('PersonCore');
$zoraAuthors = $personCore->get('zoraAuthors');

?>



<fieldset>

    <legend>Füge eine neue Beziehung zwischen einer FSW Person und Zoradokumenten hinzu</legend>
    <input
        class="ajaxButton closeButton btn btn-medium" id="addAdditionalZoraAuthor" value="add" />
    <p>&nbsp;</p>
    <div class="row-fluid" id="addZoraAuthorRowSpace">
    </div>
</fieldset>


<fieldset>
    <legend>bestehende Beziehungen</legend>
    <?php foreach ($zoraAuthors as $zoraAuthor) :?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($zoraAuthor->get('zora_name')) ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($zoraAuthor->get('zora_name_customized')) ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($zoraAuthor->get('datum_von')) ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <?php echo  $this->formRowTwb($zoraAuthor->get('datum_bis')) ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4 markItem">

                Anzahl angehängter Zoradokumente an AutorIn unter diesem Namen: <?php echo $zoraAuthor->getObject()->getNumberzoradocs(); ?>

            </div>
        </div>

        <div class="row-fluid linkMitAbstandBottom">
            <div class="span4">
                <a class="zoraAuthorUpdateButton" data-id-ZoraAuthor="<?php echo $zoraAuthor->get('id')->getValue(); ?>"  href='#'>update Zora Autor</a>
            </div>
            <div class="span4">
                <a class="zoraAuthorDeleteButton" data-id-ZoraAuthor="<?php echo $zoraAuthor->get('id')->getValue(); ?>" href='#'>delete Zora Autor</a>
            </div>
        </div>


    <?php endforeach; ?>
</fieldset>

<?php
    if (!isset($formPrepared) || $formPrepared == false) {
        echo  $this->form()->closeTag();
    }

?>




