<?php


$this->headTitle("Dies ist eine Person");


$form = $this->form;

$form->setAttribute('action', $this->url(
    'personen',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();

$personCore = $form->get('PersonCore');
$personExtended = $personCore->get('personExtended');
$zoraAuthors = $personCore->get('zoraAuthors');



$saveButtonLabel = "Speichern";

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formLabel()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

?>



<?= $this->formTwb()->openTag($form, $formType) ?>
    <div class="topButtons">
        <input type="submit" value="<?= $this->escapeHtml($saveButtonLabel) ?>"
               class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
        <a href="<?= $this->url('medien', array('action' => 'index')); ?>"
           class="ajaxButton closeButton btn btn-medium" id="closebutton">
            "passiert hier etwas?"
        </a>
    </div>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?= $this->ztbFlashMessenger()->render() ?>

    <div class="tabbable">
        <ul class="nav nav-tabs formTabs">
            <li class="active">
                <a href="#personCore"><?= $this->translate('personCore HS', 'Libadmin') ?></a>
            </li>
            <li><a href="#personExtended"><?= $this->translate('personExtended FSW', 'Libadmin') ?></a></li>
            <li><a href="#zoraAuthors"><?= $this->translate('zoraNamen FSW', 'Libadmin') ?></a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="personCore">
                <fieldset>
                    <legend>core attributes</legend>
                    <div class="row-fluid">
                        <div class="span6">
                            <?= $this->formRowTwb($personCore->get('pers_uzhshortname')) ?>
                        </div>
                        <div class="span6">
                            <?= $this->formRowTwb($personCore->get('pers_vorname')) ?>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="notes">
                    <legend>hier der Name</legend>
                    <?= $this->formRowTwb($personCore->get('pers_name')) ?>
                </fieldset>
            </div>
            <div class="tab-pane active" id="personExtended">
                <fieldset>
                    <legend>core attributes</legend>

                    <?php foreach ($personExtended as $singleExtended) :?>
                        <div class="row-fluid">
                            <div class="span6">
                                <?= $this->formRowTwb($singleExtended->get('pers_id')) ?>
                            </div>
                            <div class="span6">
                                <?= $this->formRowTwb($singleExtended->get('profilURL')) ?>
                            </div>
                        </div>

                    <?php endforeach; ?>


                </fieldset>

            </div>
            <div class="tab-pane active" id="zoraAuthors">
                <fieldset>
                    <legend>zora Namen</legend>
                    <?php foreach ($zoraAuthors as $zoraAuthor) :?>
                    <div class="row-fluid">
                        <div class="span6">
                            <?= $this->formRowTwb($zoraAuthor->get('zora_name')) ?>
                        </div>
                        <div class="span6">
                            <?= $this->formRowTwb($zoraAuthor->get('zora_name_customized')) ?>
                        </div>
                    </div>

                    <?php endforeach; ?>
                </fieldset>

            </div>


        </div>
    </div>

<?= $this->form()->closeTag(); ?>