<?php


$this->headTitle("Dies ist eine Person");


$form = $this->form;

$form->setAttribute('action', $this->url(
    'personen',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();

$personCore = $form->get('PersonCore');
$personExtended = $personCore->get('personExtended');
$zoraAuthors = $personCore->get('zoraAuthors');



$saveButtonLabel = "Speichern";

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formLabel()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

?>



<?= $this->formTwb()->openTag($form, $formType) ?>
    <div class="topButtons">
        <input type="submit" value="<?= $this->escapeHtml($saveButtonLabel) ?>"
               class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">
        <a href="<?= $this->url('medien', array('action' => 'index')); ?>"
           class="ajaxButton closeButton btn btn-medium" id="closebutton">
            "passiert hier etwas?"
        </a>
    </div>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?= $this->ztbFlashMessenger()->render() ?>



<?= $this->form()->closeTag(); ?>