<?php


//edit-zora-author kann auch im Kontext von z.B. edit (Personen) aufgerufen werden
//->dann wenn die Daten einer Person komplett zum erste Mal im Editor - Bereich der Oberfläche ngezeigt werden
if (!isset($formPrepared) || $formPrepared == false) {
    $form->prepare();
}

$personCore = $form->get('PersonCore');
$zoraAuthors = $personCore->get('zoraAuthors');

?>



<fieldset>

    <legend>Füge eine neue Beziehung zwischen einer FSW Person und Zoradokumenten hinzu</legend>
    <input
        class="ajaxButton closeButton btn btn-medium" id="addAdditionalZoraAuthor" value="add" />
    <p>&nbsp;</p>
    <div class="row-fluid" id="addZoraAuthorRowSpace">
    </div>
</fieldset>


<fieldset>
    <legend>bestehende Beziehungen</legend>
    <?php foreach ($zoraAuthors as $zoraAuthor) :?>
        <div class="row-fluid">
            <div class="hidden idZoraAuthor"><?php echo  $zoraAuthor->get('id')->getValue() ?></div>
            <div class="span4 nameZoraAuthor" style="margin-right: 10px;">
                <?php echo  $this->formRowTwb($zoraAuthor->get('zora_name')) ?>
            </div>
            <div class="span4 customizedNameZoraAuthor" style="margin-right: 10px;">
                <?php echo  $this->formRowTwb($zoraAuthor->get('zora_name_customized')) ?>
            </div>
            <div class="span2" style="margin-right: 10px;">
                <a href="#"
                   class="zoraAuthorDeleteButton">delete</a>
            </div>

            <div class="span2" style="margin-right: 10px;">
                <a href="#"
                   class="zoraAuthorUpdateButton">update</a>
            </div>
        </div>

    <?php endforeach; ?>
</fieldset>

<?php
    if (!isset($formPrepared) || $formPrepared == false) {
        echo  $this->form()->closeTag();
    }

?>




