

<?php

    $zoraDocs = $this->zoraDocs;

?>




    <?php foreach ($zoraDocs as $key => $docs): ?>

    <a name="dies ist ein Name"><!-- --></a>
    <h2 class="zoraSectionName"><?php echo $key; ?></h2>

    <ul class="skin-text-basics">

        <?php foreach ($docs as $doc): ?>

        <!--ist ein Bild vorhanden wird die Struktur unterschiedlich aufgebaut (Liste oder nicht)
        beachte: dei Ende tags der Struktur sind am Ende und müssen wieder durch entsprechende Abfragen ermittelt werden
        -->

        <?php if ($doc->getCoverLink() != null): ?>
                <li class="marginTop">
                    <div class="fluid">

            <div class="floating-box-left" >
                <img src="<?php echo  $this->changeTohttps($doc->getCoverLink())?>" />
            </div>

                <?php
                $typeFloatingBoxRight = 'floating-box-right';
                ?>

         <?php else: ?>

                <li class="marginTop-small">
                <div>
                <?php
                $typeFloatingBoxRight = 'floating-box-right-large';
                ?>

        <?php endif; ?>
            <div class="<?php echo $typeFloatingBoxRight; ?>">
            <?php echo  $doc->getSource() ?>

        <?php if ( $doc->getRelationExtern() != null && (strpos($doc->getRelationExtern(),"e-collection") == true) ||
                strpos($doc->getRelationExtern(),"lir") == true ||
                strpos($doc->getRelationExtern(),"hls") == true ||
                strpos($doc->getRelationExtern(),"ssoar") == true ||
                strpos($doc->getRelationExtern(),"hermes") == true ||
                strpos($doc->getRelationExtern(),"prokla") == true ||
                strpos($doc->getRelationExtern(),"zfmw") == true ||
                strpos($doc->getRelationExtern(),"sgg") == true ||
                strpos($doc->getRelationExtern(),"apuz") == true ||
                strpos($doc->getRelationExtern(),"224_Arni") == true ||
                strpos($doc->getRelationExtern(),"seals") == true  ||
                strpos($doc->getRelationExtern(),"zeitenblicke") == true ||
                strpos($doc->getRelationExtern(),"hsozkult") == true ||
                strpos($doc->getRelationExtern(),"gei") == true ||
                strpos($doc->getRelationExtern(),"bezg") == true ||
                strpos($doc->getRelationExtern(),"academia") == true ||

                in_array("Scientific Publication in Electronic Form",$doc->getType())    ): ?>



                <!-- Fall 1

                ein super dooper link auf einen Volltext
                -->

            <p>
                <?php if ($doc->getRelationExtern() != null) : ?>

                    <?php echo $this->internalExternalLink()->createLink($doc->getRelationExtern(), 'Volltext'); ?>
                    &nbsp;
                <?php endif; ?>


                <?php if ($doc->getSwissbibISBN() != null) : ?>

                    <?php echo $this->internalExternalLink()->createLink($doc->getSwissbibISBN(), 'swissbib'); ?>
                    &nbsp;

                <?php endif; ?>

                <?php if ($doc->getRelationZora() != null) : ?>

                    <?php echo $this->internalExternalLink()->createLink($doc->getRelationZora(), 'Zora'); ?>
                    &nbsp;
                <?php endif; ?>
            </p>





            <?php elseif (strpos(strtolower($doc->getFormat()),"pdf") == true) : ?>


                <!-- Fall 2-- ein PDF vorhanden, dies kann jedoch zugangsbeschränkt sein -->
                <p>
                <?php if ($doc->getRelationExtern() != null): ?>

                    <?php echo $this->internalExternalLink()->createLink($doc->getRelationExtern(), 'Verlagsinfo'); ?>
                    &nbsp;
                <?php endif; ?>


                <?php if ($doc->getSwissbibISBN() != null): ?>

                    <?php echo $this->internalExternalLink()->createLink($doc->getSwissbibISBN(), 'swissbib'); ?>
                    &nbsp;
                <?php endif; ?>

                <?php if ($doc->getRelationZora() != null): ?>

                    <?php echo $this->internalExternalLink()->createLink($doc->getRelationZora(), 'Volltext (evt. mit Zugangsbeschränkung)'); ?>
                    &nbsp;
                <?php endif; ?>
                </p>

                <?php else: ?>

            <p>
                <!-- Fall 3: kein PDF im Zora ich knn jedoch Verlagsinfo haben -->

                <?php if ($doc->getRelationExtern() != null): ?>

                    <?php echo $this->internalExternalLink()->createLink($doc->getRelationExtern(), 'Verlagsinfo'); ?>
                    &nbsp;
                <?php endif; ?>


                <?php if ($doc->getSwissbibISBN() != null): ?>

                    <?php echo $this->internalExternalLink()->createLink($doc->getSwissbibISBN(), 'swissbib'); ?>
                    &nbsp;
                <?php endif; ?>

                <?php if ($doc->getRelationZora() != null): ?>

                    <?php echo $this->internalExternalLink()->createLink($doc->getRelationZora(), 'Zora'); ?>
                    &nbsp;
                <?php endif; ?>
            </p>
                <?php endif; ?>
            </div>

                <!--Abschluss der Struktur - entweder mit oder ohne Bild  -->
            </div>
            </li>

        <?php endforeach; ?>
    </ul>


    <?php endforeach; ?>


