

<?php

    $qArbeiten = $this->qArbeiten;
    $all = $this->all;
    $baseURL = $this->$baseURL;
    $params = $this->params;

?>

<?php $params = $this->sortSwitcher($params) ?>

<?php if (array_key_exists('sort', $params)): ?>

    <?php if (strcmp($params['sort'],'name') == 0): ?>
        <?php $sorttext = 'alphabetische Sortierung' ?>
    <?php else: ?>
        <?php $sorttext = 'chronologische Sortierung' ?>
    <?php endif; ?>


    <a class="internal"  href="<?php echo $this->url('presentation/default', array('controller' => 'qarb','action' => 'show'), array('query' => $params)); ?>"><?php echo $sorttext; ?></a>
    <p>&nbsp;</p>

<?php endif; ?>

<ul class="type1">

    <?php foreach($qArbeiten as $qArbeit): ?>
    <li>
        <!-- noch  zu machen: meherere Autoren-->

            <p class="noMarginBottom">
                    <?php
                    if ($qArbeit->isSetProfilURL()) {

                        echo $this->internalExternalLink()->createLink($qArbeit->getProfilURL(), $qArbeit->getPersName() . ',&nbsp;' . $qArbeit->getPersVorname());

                    } else {
                        echo '<b>' . $qArbeit->getPersName() . ',&nbsp;' . $qArbeit->getPersVorname() . '</b>';
                    }
                    ?>


                <br />

                <?php echo $qArbeit->getQarbArbTitel() . '.'; ?>


                <?php
                $showDatum = false;
                foreach ($params['status'] as $status) {
                    if (strcmp($status,'abgeschlossen') == 0) {
                        $showDatum = true;
                        break;
                    }
                }
                ?>

                <?php if ($showDatum): ?>
                    &nbsp; Abschluss: <?php echo $qArbeit->getQarbArbAbschlussjahr(); ?>
                <?php endif; ?>

                <?php if ($all): ?>
                    &nbsp; (Ref.:&nbsp;
                    <?php

                        if ($qArbeit->getBetreuer1Info()->isSetProfilURL()) {
                            echo $this->internalExternalLink()->createLink($qArbeit->getBetreuer1Info()->getProfilURL(),
                                trim($qArbeit->getBetreuer1Info()->getNachName()) . '&nbsp;' . trim($qArbeit->getBetreuer1Info()->getVorName())) . ')';

                        } else {
                            echo trim($qArbeit->getBetreuer1Info()->getNachName()) . '&nbsp;' . trim($qArbeit->getBetreuer1Info()->getVorName()) . ')';
                        }

                    ?>


                <?php endif; ?>
            </p>


        <?php if ($qArbeit->isSetAbstract()): ?>
            <div>
                <a class="internal abstractCaption" href="#">mehr</a>
                <br/>
                <div class="abstractText">
                    <?php echo $qArbeit->getQarbArbAbstractInParagraphs(); ?> &nbsp;
                </div>
            </div>

        <?php endif; ?>

        <?php if ($qArbeit->isSetQarbArbURL()): ?>
            <?php if ($qArbeit->isOnlineAbgeschlosseneDiss()): ?>
                <div>
                    <?php echo $this->internalExternalLink()->createLink($qArbeit->getQarbArbURL(), 'Onlinepublikation'); ?>
                </div>
            <?php else: ?>
                <div>
                    <?php echo $this->internalExternalLink()->createLink($qArbeit->getQarbArbURL(), 'Archivexemplar der Zentralbibliothek Zürich'); ?>
                </div>
            <?php endif; ?>


        <?php endif; ?>

        <?php if ($qArbeit->isSetQarbArbISBN()): ?>
            <div>
                <?php echo $this->internalExternalLink()->createLink("http://www.swissbib.ch/Search/Results?lookfor=" . $qArbeit->getQarbArbISBN(), 'Publikation'); ?>
            </div>
        <?php endif; ?>
<br />
    </li>


    <?php endforeach; ?>
</ul>

