<!--
<div class="jumbotron">
    <h1></h1>
</div>
-->

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Backend: Administration FSW') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('letzter Update: 15.12.2014') ?></p>
                <p><a  target="_blank" href="https://github.com/guenterh/fsw"><?php echo $this->translate('Source Code') ?></a></p>
                <p><a  target="_blank" href="https://github.com/guenterh/fsw/issues"><?php echo $this->translate('todo (Fertigstellung bis Ende 2014)') ?></a></p>

            </div>
        </div>
    </div>

</div>



