<!--
<div class="jumbotron">
    <h1></h1>
</div>
-->

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Backend: Administration FSW') ?></h3>
            </div>
            <div class="panel-body">
                <p><a href="https://github.com/guenterh/fsw/commit/94e6abd8b6657848494575edc411f17586ec27d0" target="_blank"  > <?php echo $this->translate('letzter commit: 4.2.2015') ?></a></p>
                <p><a  target="_blank" href="https://github.com/guenterh/fsw"><?php echo $this->translate('Source Code') ?></a></p>
                <p><a  target="_blank" href="https://github.com/guenterh/fsw/issues"><?php echo $this->translate('offene issues') ?></a></p>

            </div>
        </div>
    </div>

</div>



