<?php


$this->headTitle("Dies ist der Titel fuer Medien");


$form = $this->form;

$form->setAttribute('action', $this->url(
    'medien',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();



$saveButtonLabel = "Speichern";

$formType = 'horizontal';

// Force Libadmin text domain (@todo cleaner way?)
$this->formLabelTwb()->setTranslatorTextDomain('Libadmin');
$this->formLabel()->setTranslatorTextDomain('Libadmin');
$this->formSelectTwb()->setTranslatorTextDomain('Libadmin');

//$test = $this->url('medien',array('action' => 'edit', 'id' => $form->get('id')->getValue()), array( 'query' =>  ['jdjdj' => 'jdjdj', 'bla' => 'kdkdk']));

$form->setAttribute('action',$this->url('medien',array('action' => 'edit', 'id' => $form->get('id')->getValue())));

?>



<?php echo  $this->formTwb()->openTag($form, $formType) ?>
    <fieldset>
    <div class="topButtons">
        <input type="submit" value="<?php echo  $this->escapeHtml($saveButtonLabel) ?>"
               class="submitButton btn btn-primary btn-medium" id="submitbutton" name="submit">

        <a href="<?php echo  $this->url('medien', array('action' => 'delete','id'=> $form->get('id')->getValue())); ?>"
           class="ajaxButton closeButton btn btn-medium" id="closebutton">
            "Satz loeschen"


        <a href="<?php echo  $this->url('medien', array('action' => 'closeContent')); ?>"
           class="ajaxButton closeButton btn btn-medium" id="closebutton">
            "Hier schliessen"
        </a>
    </div>
    </fieldset>

    <fieldset class="edit_legend_title_medien">

        <legend><?php echo $this->escapeHtml($form->get('gespraechstitel')->getValue()); ?></legend>

    </fieldset>


<?php echo  $this->ztbFlashMessenger()->render() ?>

    <fieldset class="general">
        <div class="container-fluid">
            <div class="row-fluid">

                <div class="span12"><?php echo  $this->formRowTwb($form->get('gespraechstitel')) ?></div>
            </div>
            <!--
            <div class="row-fluid">
                <div class="medienKommentar">Zum Beispiel: Die Schweiz am Rande des Bürgerkriegs</div>
            </div>
            -->
            <div class="row-fluid">

                <div class="span12"><?php echo  $this->formRowTwb($form->get('sendetitel')) ?></div>
            </div>

            <!--
            <div class="row-fluid">
                <div class="medienKommentar ">Zum Beispiel: Radio SRF 2, Kontext</div>
            </div>
            -->


            <div class="row-fluid">

                <div class="span12"><?php echo  $this->formRowTwb($form->get('id')) ?></div>
            </div>

            <div class="row-fluid">

                <div class="span12"><?php echo  $this->formRowTwb($form->get('mit_id_per_extended')) ?></div>
            </div>



            <div class="row-fluid">

                <div class="span12"><?php echo  $this->formRowTwb($form->get('medientyp')) ?></div>
            </div>

            <div class="row-fluid">

                <div class="span12"><?php echo  $this->formRowTwb($form->get('icon')) ?></div>
            </div>

            <div class="row-fluid">

                <div class="span12"><?php echo  $this->formRowTwb($form->get('link')) ?></div>
            </div>

            <div class="row-fluid">

                <div class="span12"><?php echo  $this->formRowTwb($form->get('datum')) ?></div>
            </div>

        </div>



    </fieldset>


<?php echo  $this->form()->closeTag(); ?>